import os
from app.tasks import celery_app
from app.services.llm_service import LLMService
from app.services.tts_service import TTSService
from app.services.image_service import ImageService
from app.services.diagram_service import DiagramService
from app.services.video_service import VideoService


@celery_app.task(bind=True)
def generate_video_task(self, topic: str, video_type: str, language: str, options: dict = None):
    """
    Celery Background Task:
    1. Generate script
    2. Generate audio narration
    3. Generate scene visuals
    4. Build final video
    """

    options = options or {}

    # Ensure output directory exists
    output_dir = os.getenv("OUTPUT_DIR", "./output")
    os.makedirs(output_dir, exist_ok=True)

    # Initialize services
    llm_service = LLMService()
    tts_service = TTSService()
    image_service = ImageService()
    diagram_service = DiagramService()
    video_service = VideoService()

    try:
        # STEP 1: Generate Script
        self.update_state(
            state="PROGRESS",
            meta={"progress": 10, "message": "Generating script...", "current_step": "script"}
        )

        script = llm_service.generate_script(topic, video_type, language)

        scenes = script.get("scenes", [])
        if not scenes:
            raise Exception("No scenes generated by LLM")

        # STEP 2: Generate Audio
        self.update_state(
            state="PROGRESS",
            meta={"progress": 20, "message": "Generating voice narration...", "current_step": "audio"}
        )

        # Build narration text
        # FIX: `narration` does NOT exist in your script. Should use scene["text"]
        full_narration = " ".join([
            scene.get("text") or scene.get("voiceover") or "" for scene in scenes
        ]).strip()

        if not full_narration:
            full_narration = script.get("description", "No narration provided.")

        audio_path = tts_service.generate_audio(
            full_narration,
            provider=options.get("tts_provider", "openai")
        )

        # STEP 3: Generate Visuals
        scene_clips = []
        total_scenes = len(scenes)

        # INTRO
        intro_clip = video_service.add_intro(script.get("title", topic))
        scene_clips.append(intro_clip)

        for idx, scene in enumerate(scenes):

            progress = 30 + int((idx / total_scenes) * 50)
            self.update_state(
                state="PROGRESS",
                meta={
                    "progress": progress,
                    "message": f"Creating scene {idx + 1}/{total_scenes}...",
                    "current_step": f"scene_{idx + 1}"
                }
            )

            visual_type = scene.get("visual_type", "image")
            text_overlay = scene.get("visual_text") or scene.get("text")
            duration = scene.get("duration", 5)

            # Prompt for image/diagram
            prompt = (
                scene.get("visual_prompt")
                or scene.get("text")
                or topic
            )

            # ----- DIAGRAM -----
            if visual_type in ("diagram", "flowchart"):
                image_path = diagram_service.create_diagram_from_text(prompt)

            # ----- TEXT SCENE -----
            elif visual_type == "text_overlay":
                clip = video_service.create_text_scene(
                    text=text_overlay,
                    duration=duration
                )
                scene_clips.append(clip)
                continue

            # ----- AI IMAGE -----
            else:
                image_path = image_service.generate_image(prompt)

            # Create final scene clip
            clip = video_service.create_scene_clip(
                image_path=image_path,
                duration=duration,
                text_overlay=text_overlay,
                transition=scene.get("transition", "fade")
            )
            scene_clips.append(clip)

        # OUTRO
        outro_clip = video_service.add_outro()
        scene_clips.append(outro_clip)

        # STEP 4: Compose Final Video
        self.update_state(
            state="PROGRESS",
            meta={"progress": 85, "message": "Composing final video...", "current_step": "compose"}
        )

        output_path = os.path.join(output_dir, f"{self.request.id}.mp4")

        video_path = video_service.compose_video(
            scene_clips=scene_clips,
            audio_path=audio_path,
            output_path=output_path
        )

        # STEP 5: Return Final Result
        self.update_state(
            state="PROGRESS",
            meta={"progress": 95, "message": "Finalizing...", "current_step": "finalize"}
        )

        return {
            "success": True,
            "video_path": video_path,
            "title": script.get("title", topic),
            "duration": script.get("duration_seconds", 0),
            "scenes_count": len(scenes)
        }

    except Exception as e:
        return {
            "success": False,
            "error": f"Video generation failed: {str(e)}"
        }
